### ISSUE TITLE
Unable to Send Tokens

### ISSUE THREAD

**Issue by Anastik** [jcnelson/cli-blockstack#10]
When I try to send tokens I get an error saying the account isn't found. I know the account is there because I created its keychain and can see the address when I run it through the Testnet homepage. Here's the error that gets returned:

Kitsanas-MacBook-Pro:cli-blockstack Kitsana.Dounglomchan$ blockstack-cli -t send_tokens myKmqo1ZoqKuhw9KcAUJCZjtNij1Eu9NFK stacks 1000000 7b67da8665e6417ded72e0457e1640690a67870bcb163a69f4f490d6edf047d501
Error: Account not found
    at /Users/Kitsana.Dounglomchan/cli-blockstack/lib/network.js:443:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Account not found

**Comment by jcnelson** [comment]
Hey @Anastik, the tokens don't become available until they show up with the `balance` command.  Did it work after waiting a couple minutes?

**Comment by jcnelson** [comment]
Going to go ahead and close this since AFAIK it's working.  Please re-open if you still have problems.
