### ISSUE TITLE
get_blockchain_record fails

### ISSUE THREAD

**Issue by jehunter5811** [jcnelson/cli-blockstack#13]
To replicate, run the blockstack-cli get_blockchain_record command for any id. You should get an error like this: 

Error: Bad response status: 404
    at /Users/slideroom/Documents/GitHub/cli-blockstack/lib/network.js:325:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Bad response status: 404

**Comment by jcnelson** [comment]
Thanks for the heads up!  Looks like the CLI is using an API endpoint that doesn't exist on the `master` branch of Blockstack Core.  Will add in some compatibility code.

**Comment by jcnelson** [comment]
Fixed in b33afb7
