### ISSUE TITLE
Transfer error "Invalid command arguments"

### ISSUE THREAD

**Issue by john-light** [jcnelson/cli-blockstack#17]
To transfer I enter:

`blockstack-cli -t transfer blockstack.id2 mgmeYPFDSsUhMKbyovahGBMw5kyDdQxVyB 10eb132354e6194979f514e90f2ebd04914b9d695751ae083bec98409c2385ca01 d962dea9ff08f3eabdacaa5cd8dd9000f14730ad6df4a3fe6a59be401e79dba901`

Broken down by the format the Help file suggests, that is: `blockstack-cli -t transfer BLOCKSTACK_ID NEW_ID_ADDRESS OWNER_KEY PAYMENT_KEY`

Which returns:

`Invalid command arguments`
`Command: transfer`

The help file says the correct command is:

`transfer BLOCKSTACK_ID NEW_ID_ADDRESS KEEP_ZONEFILE OWNER_KEY PAYMENT_KEY` 

I also tried pre-pending the NEW_ID_ADDRESS with "ID-" and that did not work either.

I'm wondering what about the command I gave is invalid/ malformed?

Can you please share a properly formatted transfer command so I can check that this isn't user error?

**Comment by jcnelson** [comment]
Hey @john-light,

Not sure if this was resolved via a separate channel, but the command format is:

```
blockstack-cli -t transfer blockstack.id2 ID-mgmeYPFDSsUhMKbyovahGBMw5kyDdQxVyB False 10eb132354e6194979f514e90f2ebd04914b9d695751ae083bec98409c2385ca01 d962dea9ff08f3eabdacaa5cd8dd9000f14730ad6df4a3fe6a59be401e79dba901
```

You need the `ID-` prefix on the new owner address, and you forgot the `KEEP_ZONEFILE` argument.

**Comment by john-light** [comment]
Thanks for following up! I did get it figured out.
