### ISSUE TITLE
Error Registering Sub-Domain

### ISSUE THREAD

**Issue by Anastik** [jcnelson/cli-blockstack#7]
Kitsanas-MacBook-Pro:cli-blockstack Kitsana.Dounglomchan$ blockstack-cli -t register_subdomain satoshi.kitsana.id2 b672101307b383f259e850aaf8b7b367f9f3e34af61448816085ed6b4a6fc3c301 http://testnet.blockstack.org:4000 http://testnet.blockstack.org:30000
connectToGaiaHub: http://testnet.blockstack.org:4000/hub_info
{
  "status": false,
  "error": "Subdomain cannot be safely registered",
  "onChainNameInfo": {
    "status": "registered",
    "grace_period": false,
    "address": "mt2JsvcBvk8SNes4n1ZpCzmZ1qongDFMAL",
    "zonefile": "$ORIGIN kitsana.id2\n$TTL 3600\n_http._tcp\tIN\tURI\t10\t1\t\"http://testnet.blockstack.org:4000/hub/1DWMasXD7ihBbYPT4SbSP5ZE9rD5gNuQBS/profile.json\"\n\n",
    "expire_block": 54534,
    "blockchain": "bitcoin",
    "last_txid": "29905bd527e1df602f13a9e6800da6cb4b116b664057813d6f547516512bf116",
    "zonefile_hash": "0c57ce7eb8828632dae390c318b27ff49c4dc739",
    "renewal_deadline": 59534
  },
  "isNameAvailable": true

**Comment by jcnelson** [comment]
Hey @Anastik,

There needs to be a subdomain registrar running for `kitsana.id2`.  The one that is running on `http://testnet.blockstack.org:30000` is for `personal.id2`.  Will update the page to explain this better :)

If you want to register a subdomain on `kitsana.id2`, you can set up and run your own subdomain registrar for it locally by following these instructions: https://github.com/blockstack/subdomain-registrar

**Comment by Anastik** [comment]
Gotcha @jcnelson...thanks for the response.

I got the same error when I tried to register on the personal.id2 subdomain. I'm assuming this is probably because I'm not the owner of the above.
