### ISSUE TITLE
Feature Request (Price for BLOCKSTACK_ID on Testnet)

### ISSUE THREAD

**Issue by Anastik** [jcnelson/cli-blockstack#9]
Maybe adding a sentence on the Testnet page, or even a command line feature, that shows how much it'll cost to register an "id2" on the Testnet, so a person can ensure they have enough funds to cover the entire cost. 

I was having problems registering a name, but then I figured out I just didn't have enough Stacks associated with my address. I "turned on the faucet" to get some more and then the registration went through with no problems.  

I figured this out after using the "Blockstack-CLI price BLOCKSTACK_ID" command (which worked great BTW!)

So probably just a sentence or two on the Stacks Testnet page would be helpful for new users.

**Comment by jcnelson** [comment]
Sounds good!  Will do.
